# Generated by Django 2.2.19 on 2023-01-04 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230104_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='gpoup',
            new_name='group',
        ),
    ]
